[package]
name = "phichain-assets"
version = "1.0.0-beta.3"
edition = "2021"

[dependencies]
bevy = { version = "0.15.1", default-features = false, features = [
    "animation",
    "bevy_asset",
    "bevy_gilrs",
    "bevy_scene",
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_gltf",
    "bevy_render",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "multi_threaded",
    "png",
    "hdr",
    "x11",
    "bevy_gizmos",
    "tonemapping_luts",
    "default_font",
    "webgl2",
    "bevy_debug_stepping",
] }
bevy_kira_audio = { version = "0.22.0", features = [
    "mp3",
    "ogg",
    "flac",
    "wav",
] }
bevy_asset_loader = "0.22.0"
bevy_egui = { version = "0.32.0", optional = true }

[features]
egui = ["dep:bevy_egui"]
